// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(BolsaTrabajoContext))]
    partial class BolsaTrabajoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Model.Alumno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnioCurso")
                        .HasColumnType("int");

                    b.Property<string>("ApeAlumno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CantMatAp")
                        .HasColumnType("int");

                    b.Property<int>("CarreraId")
                        .HasColumnType("int");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<string>("Legajo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NomAlumno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<float>("Promedio")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("CarreraId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Legajo")
                        .IsUnique();

                    b.ToTable("Alumnos");
                });

            modelBuilder.Entity("Domain.Model.Carrera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Duracion")
                        .HasColumnType("int");

                    b.Property<string>("NomCarrera")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("NomCarrera")
                        .IsUnique();

                    b.ToTable("Carreras");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Departamento = "Ingeniería",
                            Duracion = 5,
                            NomCarrera = "Ingeniería en Sistemas de Información"
                        },
                        new
                        {
                            Id = 2,
                            Departamento = "Ingeniería",
                            Duracion = 5,
                            NomCarrera = "Ingeniería Mecánica"
                        },
                        new
                        {
                            Id = 3,
                            Departamento = "Ingeniería",
                            Duracion = 5,
                            NomCarrera = "Ingeniería Química"
                        },
                        new
                        {
                            Id = 4,
                            Departamento = "Ingeniería",
                            Duracion = 5,
                            NomCarrera = "Ingeniería Industrial"
                        },
                        new
                        {
                            Id = 5,
                            Departamento = "Ingeniería",
                            Duracion = 5,
                            NomCarrera = "Ingeniería Civil"
                        });
                });

            modelBuilder.Entity("Domain.Model.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Rubro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("RazonSocial")
                        .IsUnique();

                    b.ToTable("Empresas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Empresa de desarrollo de software",
                            RazonSocial = "TechCorp S.A.",
                            Rubro = "Tecnología"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Desarrollo de software a medida y consultoría IT",
                            RazonSocial = "DataSoft Rosario S.A.",
                            Rubro = "Tecnología"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Servicios de infraestructura cloud y ciberseguridad",
                            RazonSocial = "NubeCloud Argentina",
                            Rubro = "Tecnología"
                        });
                });

            modelBuilder.Entity("Domain.Model.Oferta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaDesde")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaHasta")
                        .HasColumnType("datetime2");

                    b.Property<int>("TipoOfertaId")
                        .HasColumnType("int");

                    b.Property<string>("TipoVinculo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("TipoOfertaId");

                    b.ToTable("Ofertas");
                });

            modelBuilder.Entity("Domain.Model.RequisitoOferta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EsExcluyente")
                        .HasColumnType("bit");

                    b.Property<int>("OfertaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OfertaId");

                    b.ToTable("RequisitosOferta");
                });

            modelBuilder.Entity("Domain.Model.TipoOferta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("TiposOferta");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Pasantía"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Primer empleo"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Empleo part-time"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Empleo full-time"
                        });
                });

            modelBuilder.Entity("Domain.Model.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Email = "admin@bolsatrabajo.com",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "3/UhTWW1eosf/i6p2ydV5T/aANktq+KOQdvFvt7j9H4=",
                            Salt = "RvmlmT923wpd20J6N8L3coCXmcKeclZ+2DJMBXdLQPE=",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("Domain.Model.Alumno", b =>
                {
                    b.HasOne("Domain.Model.Carrera", "Carrera")
                        .WithMany()
                        .HasForeignKey("CarreraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Carrera");
                });

            modelBuilder.Entity("Domain.Model.Oferta", b =>
                {
                    b.HasOne("Domain.Model.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Model.TipoOferta", "TipoOferta")
                        .WithMany()
                        .HasForeignKey("TipoOfertaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("TipoOferta");
                });

            modelBuilder.Entity("Domain.Model.RequisitoOferta", b =>
                {
                    b.HasOne("Domain.Model.Oferta", "Oferta")
                        .WithMany("Requisitos")
                        .HasForeignKey("OfertaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Oferta");
                });

            modelBuilder.Entity("Domain.Model.Oferta", b =>
                {
                    b.Navigation("Requisitos");
                });
#pragma warning restore 612, 618
        }
    }
}
